apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: k8s-operator-role
  namespace: k8s-operator
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["mycompany.com"]
    resources: ["examples"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]