apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: k8s-operator-rolebinding
  namespace: k8s-operator
subjects:
  - kind: ServiceAccount
    name: k8s-operator-sa
    namespace: k8s-operator
roleRef:
  kind: Role
  name: k8s-operator-role
  apiGroup: rbac.authorization.k8s.io